### ISSUE TITLE
Questions about rocpack and rocfire components 

### ISSUE THREAD

**Issue by aerospaceDoDo** [IllinoisRocstar/Rocstar#12]
Dose anyone can tell me that where I can find the components of rocpack and rocfire in the Rocstar suite? I'm new to rocstar and I need these components to continue my work. 
Looking forward to your reply. Thank you .

**Comment by xyzxyz-321** [comment]
Hello, my dear friend, I am also learning to use this program, I encountered some problems during the installation process, can you answer me, thank you!

**Comment by msafdari1234** [comment]
Both Rocpacj and Rocfire are proprietary software. Robust version of rocpack is commercially available for purchase. If you are interested please send your request to rocpack@illinoisrocstar.com. Rocfire is still under research and development.
