### ISSUE TITLE
Question about Rocstar on GPU

### ISSUE THREAD

**Issue by giacrossi** [IllinoisRocstar/Rocstar#13]
Hello,

I don't know if it's right to open an issue for this question, I just would like to know if is there already a plan for enabling Rocstar on heterogeneous devices, such as GPU, or a development version that already started to explore such porting.

**Comment by msafdari1234** [comment]
Hi, thanks for your inquiry. We are constantly looking at those options. Rocstar solvers can mostly benefit from heterogeneous platform. We have an early version of our structural mechanics solver on GPU, but it is not ready for outside use. Rocstar has a very modular architecture, and you can easily add your own solvers to it. If you are interested in pursuing that option, let me know.
