### ISSUE TITLE
compile problem

### ISSUE THREAD

**Issue by sunboyagn** [IllinoisRocstar/Rocstar#22]
I have meet the problem, when I run the command that make -j$(proc).Then,some error happened.can anyone have the idea to solve it.
[ 94%] Linking CXX executable ../../bin/rflumap
[ 94%] Linking CXX executable ../../bin/rflupart
[ 94%] Linking CXX executable ../../bin/rfluinit
/bin/ld: ../../lib/libRocflu.so.5.0.2: undefined reference to `mpi_initialized_'
/bin/ld: ../../lib/libRocflu.so.5.0.2: undefined reference to `mpi_reduce_'
/bin/ld: ../../lib/libRocflu.so.5.0.2: undefined reference to `mpi_wait_'
/bin/ld: ../../lib/libRocflu.so.5.0.2: undefined reference to `mpi_comm_size_'
/bin/ld: ../../lib/libRocflu.so.5.0.2: undefined reference to `mpi_send_'
/bin/ld: ../../lib/libRocflu.so.5.0.2: undefined reference to `mpi_barrier_'
/bin/ld: ../../lib/libRocflu.so.5.0.2: undefined reference to `mpi_allreduce_'
/bin/ld: ../../lib/libRocflu.so.5.0.2: undefined reference to `mpi_attr_get_'
/bin/ld: ../../lib/libRocflu.so.5.0.2: undefined reference to `mpi_abort_'
/bin/ld: ../../lib/libRocflu.so.5.0.2: undefined reference to `mpi_isend_'
/bin/ld: ../../lib/libRocflu.so.5.0.2: undefined reference to `mpi_comm_rank_'
/bin/ld: ../../lib/libRocflu.so.5.0.2: undefined reference to `mpi_recv_'
/bin/ld: ../../lib/libRocflu.so.5.0.2: undefined reference to `mpi_bcast_'
/bin/ld: ../../lib/libRocflu.so.5.0.2: undefined reference to `mpi_finalize_'
collect2: error: ld returned 1 exit status
make[2]: *** [RocfluidMP/Rocflu/CMakeFiles/rflumap.dir/build.make:173: bin/rflumap] Error 1
make[1]: *** [CMakeFiles/Makefile2:561: RocfluidMP/Rocflu/CMakeFiles/rflumap.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/bin/ld: CMakeFiles/rfluinit.dir/__/utilities/rocflu/init/rfluinit.F90.o: in function `rfluinit_':
rfluinit.F90:(.text+0x224): undefined reference to `mpi_init_'
/bin/ld: ../../lib/libRocflu.so.5.0.2: undefined reference to `mpi_initialized_'
/bin/ld: ../../lib/libRocflu.so.5.0.2: undefined reference to `mpi_reduce_'
/bin/ld: ../../lib/libRocflu.so.5.0.2: undefined reference to `mpi_wait_'
/bin/ld: ../../lib/libRocflu.so.5.0.2: undefined reference to `mpi_comm_size_'
/bin/ld: ../../lib/libRocflu.so.5.0.2: undefined reference to `mpi_send_'
/bin/ld: ../../lib/libRocflu.so.5.0.2: undefined reference to `mpi_barrier_'
/bin/ld: ../../lib/libRocflu.so.5.0.2: undefined reference to `mpi_allreduce_'
/bin/ld: ../../lib/libRocflu.so.5.0.2: undefined reference to `mpi_attr_get_'
/bin/ld: ../../lib/libRocflu.so.5.0.2: undefined reference to `mpi_abort_'
/bin/ld: ../../lib/libRocflu.so.5.0.2: undefined reference to `mpi_isend_'
/bin/ld: ../../lib/libRocflu.so.5.0.2: undefined reference to `mpi_comm_rank_'
/bin/ld: ../../lib/libRocflu.so.5.0.2: undefined reference to `mpi_recv_'
/bin/ld: ../../lib/libRocflu.so.5.0.2: undefined reference to `mpi_bcast_'
/bin/ld: ../../lib/libRocflu.so.5.0.2: undefined reference to `mpi_finalize_'
collect2: error: ld returned 1 exit status
/bin/ld: CMakeFiles/rflupart.dir/__/make[2]: *** [RocfluidMP/Rocflu/CMakeFiles/rfluinit.dir/build.make:333: bin/rfluinit] Error 1
utilities/rocflu/part/rflupart.F90.o: in function `rflupart_':make[1]: *** [CMakeFiles/Makefile2:621: RocfluidMP/Rocflu/CMakeFiles/rfluinit.dir/all] Error 2

rflupart.F90:(.text+0x224): undefined reference to `mpi_init_'
/bin/ld: ../../lib/libRocflu.so.5.0.2: undefined reference to `mpi_initialized_'
/bin/ld: ../../lib/libRocflu.so.5.0.2: undefined reference to `mpi_reduce_'
/bin/ld: ../../lib/libRocflu.so.5.0.2: undefined reference to `mpi_wait_'
/bin/ld: ../../lib/libRocflu.so.5.0.2: undefined reference to `mpi_comm_size_'
/bin/ld: ../../lib/libRocflu.so.5.0.2: undefined reference to `mpi_send_'
/bin/ld: ../../lib/libRocflu.so.5.0.2: undefined reference to `mpi_barrier_'
/bin/ld: ../../lib/libRocflu.so.5.0.2: undefined reference to `mpi_allreduce_'
/bin/ld: ../../lib/libRocflu.so.5.0.2: undefined reference to `mpi_attr_get_'
/bin/ld: ../../lib/libRocflu.so.5.0.2: undefined reference to `mpi_abort_'
/bin/ld: ../../lib/libRocflu.so.5.0.2: undefined reference to `mpi_isend_'
/bin/ld: ../../lib/libRocflu.so.5.0.2: undefined reference to `mpi_comm_rank_'
/bin/ld: ../../lib/libRocflu.so.5.0.2: undefined reference to `mpi_recv_'
/bin/ld: ../../lib/libRocflu.so.5.0.2: undefined reference to `mpi_bcast_'
/bin/ld: ../../lib/libRocflu.so.5.0.2: undefined reference to `mpi_finalize_'
collect2: error: ld returned 1 exit status
make[2]: *** [RocfluidMP/Rocflu/CMakeFiles/rflupart.dir/build.make:319: bin/rflupart] Error 1
make[1]: *** [CMakeFiles/Makefile2:591: RocfluidMP/Rocflu/CMakeFiles/rflupart.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

**Comment by mdbrandy** [comment]
First, Illinois Rocstar is out of business and there are no technical staff
members left to answer your question.

As a guess, all the errors appear to be related to the MPI libraries, so if
I were you, I'd look to see if you have the prerequisites installed
correctly.

**Comment by sunboyagn** [comment]
For a while,I finally solve the problem and I write how I solve the issue and hope can help others.Firstly, the reason for this issue is that the version of the MPI library you are using is too high. It is strongly recommended to use MPI library version 2-1.4.1. Of course, when you compile using this library, it is highly likely that Camke will send errors, and the solution is simple: choose a lower version of CMAKE.
