### ISSUE TITLE
make error on rflupart

### ISSUE THREAD

**Issue by Langolyers** [IllinoisRocstar/Rocstar#5]
I succesfully compiled both IMPACT and the metis libraries, and cmake works without issues. However, when running `make -j$(nproc)` i get errors on rflumap, rfluinit and rflupart. I'm on Ubuntu 18.04 with gcc 7.5.0. Logs are below. Let me know if there's more information you need. Thanks for the support.

cmake:
`-- Setting build type to 'Release' as none was specified.
-- A library with BLAS API found.
-- A library with LAPACK API found.
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.13") found components:  doxygen dot 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/augusto/Downloads/rocstar-master`

make log is in the file:
[make_log.txt](https://github.com/IllinoisRocstar/Rocstar/files/4616320/make_log.txt)

**Comment by msafdari1234** [comment]
Looks like CMAKE has not identified MPI compilers properly. Try `ccmake .` on the build folder, hit `t` for adv mode, and look at `CMAKE_CXX_COMPILER`, `CMAKE_C_COMPILER`, and `CMAKE_Fortran_COMPILER`. Make sure are all pointing to `mpicxx`, `mpicc`, and `mpifort` respectively.

**Comment by Langolyers** [comment]
The proposed solution worked, CMAKE was not finding the compilers.
