### ISSUE TITLE
Unable to run ACM aft Windows/Static port, Cygwin compile, and CygwinStatic compile

### ISSUE THREAD

**Issue by rudyverderber** [IllinoisRocstar/Rocstar#6]
Hello,

I have been unable to run ACM using a windows static port, Cygwin compile or Cygwin -DSTATIC_LINK compile.

I think the Cygwin compile version should work.  When I finish the compile, the libraries begin with "cyg" instead of "lib" and end in "-(version #).dll" instead of ".so." When I run rocstar, it bombs immediately with open library errors.  So, I copied the IMPACT dlls to the local directory.  The it runs with errors about the dlls that are in the IMPACT 

bin directory not being in the IMPACT lib directory.  So I copied the IMPACT dlls from the bin directory to the lib directory.   Then it complains the Rocstar dlls are not in the IMPACT lib directory.  So I copied the Rocstar dlls to the IMPACT lib directory.

All these directories are included in my LD_LIBRARY_PATH.  It is not clear why I should have to copy the files, but the rocstar seems to find the dlls.

I have created STATIC LINK versions.  They also have problems about dlls.  I expected it to be a full static link.   And, they do not get farther than the dynamic library version.  

Also, the ACM does not include Rocin files, so I created them based on the manual.

I have attached the output from my 4 dll runs.

What am I doing wrong?

Regards,

Rudy
[RunOut.txt](https://github.com/IllinoisRocstar/Rocstar/files/4640298/RunOut.txt)

**Comment by msafdari1234** [comment]
Rocstar is officially not fully supporting Windows environments. Unfortunately we cannot support you with these questions.
