### ISSUE TITLE
How do you create the ACM HDF file?

### ISSUE THREAD

**Issue by rudyverderber** [IllinoisRocstar/Rocstar#7]
For the ACM example,  I created a fluid_in_00.000000.txt file as shown below from the Rocin UG.  Rocstar per the tutorial also requires an HDF file as input.   Is that correct?  If yes, how do I create or obtain the HDF4 file for ACM?
@Proc: 0
@Files: fluid*_00.00_0000.hdf
@Panes: 1 5 9 12 17
@Material: fluid
@Proc: 1
@Files: fluid*_00.00_0000.hdf
@Panes: 2 6 10 13 18
@Material: fluid
@Proc: 2
@Files: fluid*_00.00_0000.hdf
@Panes: 3 7 11 14 19
@Material: fluid
@Proc: 3
@Files: fluid*_00.00_0000.hdf
@Panes: 4 8 12 16 20
@Material: fluid

**Comment by msafdari1234** [comment]
The HDF4 files are generated by Rocprep. A combination of input preprocessors are used to generate these file. You can study [ACM_RocfluTest.C](https://github.com/IllinoisRocstar/Rocstar/blob/master/testing/src/ACM_RocfluTest.C) for details.
