### ISSUE TITLE
rocprep error

### ISSUE THREAD

**Issue by Wangduu** [IllinoisRocstar/Rocstar#9]
I try to run rocprep but this error occurred:

`Fri Sep  4 19:58:51 2020: Checking NDA files

Ending phase: Check NDA Files for module RocfloProcessor.
Ending phase: Check NDA Files for module RocfracProcessor.
***************************************************************************

Fri Sep  4 19:58:51 2020: Extracting NDA files to rocstar dataset

Ending phase: Extract NDA Files for module RocfloProcessor.
Ending phase: Extract NDA Files for module RocfracProcessor.
***************************************************************************

Fri Sep  4 19:58:52 2020: Running preprocessor codes to make rocstar dataset

makeflo  ep-PLOT3D.grd 8 ep.top ep.grda > /home/tanghulu/roccase//makeflo.log 2>&1

--->ERROR in RocfloProcessor: Preprocessor Code Run failure:
makeflo  ep-PLOT3D.grd 8 ep.top ep.grda > /home/tanghulu/roccase//makeflo.log 2>&1

Ending phase: Run Preprocessors for module RocfloProcessor.

--->ERROR in RocfracProcessor: Preprocessor Code Run failure:
rfracprep -np 8  > /home/tanghulu/roccase//rfracprep.log 2>&1

Ending phase: Run Preprocessors for module RocfracProcessor.

--->ERROR in RocfaceProcessor: Preprocessor Code Run failure:
surfdiver Rocflo/Rocin/ifluid_in_00.000000.txt Rocfrac/Rocin/isolid_in_00.000000.txt Rocman/RocfloRocfrac/ > surf_flofrac.log 2>&1

Ending phase: Run Preprocessors for module RocfaceProcessor.
***************************************************************************

***************************************************************************

Run terminated with error: Errors occurred during preprocessing.

***************************************************************************`

**Comment by xyzxyz-321** [comment]
hello,
    I am also using this program, but I don't know how to configure environment variables. Can you give me some answers? Thank you!
The following environment variables need to be set before building Rocstar.
CC=mpicc
CXX=mpicxx
FC=mpif90
CMAKE_PREFIX_PATH=/full/path/to/metis:/absolute/path/to/tpl
Note that CMAKE_PREFIX_PATH should be a colon-separated list of paths to the TPL
installation locations if they are in places other than typical system paths (e.g. /usr,
/usr/local). CMake will automatically look in ${CMAKE_PREFIX_PATH}/{include,lib,lib64}
for needed libraries and include files.
In addition, for the purposes of this guide, the following variables will be used to indicate
the the distribution and installation directories.
ROCSTAR_SOURCE=/path/to/distribution/directory
ROCSTAR_BUILD=/path/to/installation/directory
ROCSTAR_EXAMPLES=${ROCSTAR_SOURCE}/Examples/NDAs
Note that ROCSTAR_SOURCE should not be the same path as ROCSTAR_BUILD. If it
does not exist, create the build directory and cd into it with the following commands.

**Comment by msafdari1234** [comment]
please follow the directions given [here](https://github.com/IllinoisRocstar/Rocstar/blob/master/README.md).

**Comment by Wangduu** [comment]
@msafdari1234  This erro occurred when I use the command 
`rocprep -A -b -o 1 6 -f 3 9 -d $ROCSATR_EXAMPLES/ElasticPiston -t ./elasticpiston -n 8`
It seems rocflu and rocfrac do not exist in the lates version,I wonder if these modules will be available in future version cause there are many problems when I try to install the old version .
Hope to receive your reply.

**Comment by Wangduu** [comment]
@xyzxyz-321 Just follow the directions in README.md, thoes variables can be set in cmake.

**Comment by msafdari1234** [comment]
@Wangduu We have removed rocfrac from the project. It is being replaced with a new state-of-art structural solver. If you want rocfrac, unfortunately you will need to use [legacy version](https://github.com/IllinoisRocstar/Rocstar-legacy). We will be releasing new structural solver soon.

**Comment by Wangduu** [comment]
@msafdari1234 Thanks for your reply, looking forward to the new structural solver!
